FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

WORKDIR /app/src/ebay-mcp

ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml /app/
RUN uv pip install --system "mcp[cli]" requests pydantic starlette uvicorn httpx

ADD src /app/src

ENV EBAY_SANDBOX=false

EXPOSE 8000

CMD ["python", "server_http.py"]
